export const FETCH_TRENDING = 'FETCHING_TRENDING';
export const FETCHING_TRENDING_SUCCESS = 'FETCHING_TRENDING_SUCCESS';
export const FETCHING_TRENDING_FAILURE = 'FETCHING_TRENDING_FAILURE';

export const FETCH_SINGLE_TVSHOW = 'FETCH_SINGLE_TVSHOW';
export const FETCH_SINGLE_TVSHOW_SUCCESS = 'FETCH_SINGLE_TVSHOW_SUCCESS';
export const FETCH_SINGLE_TVSHOW_FAILURE = 'FETCH_SINGLE_TVSHOW_FAILURE';

export const FETCH_TRAILER = 'FETCH_TRAILER';
export const FETCH_TRAILER_SUCCESS = 'FETCH_TRAILER_SUCCESS';
export const FETCH_TRAILER_FAILURE = 'FETCH_TRAILER_FAILURE';
