export const FETCH_TRENDING = 'FETCHING_TRENDING';
export const FETCHING_TRENDING_SUCCESS = 'FETCHING_TRENDING_SUCCESS';
export const FETCHING_TRENDING_FAILURE = 'FETCHING_TRENDING_FAILURE';

export const FETCH_SINGLE_TVSHOW = 'FETCH_SINGLE_TVSHOW';
export const FETCH_SINGLE_TVSHOW_SUCCESS = 'FETCH_SINGLE_TVSHOW_SUCCESS';
export const FETCH_SINGLE_TVSHOW_FAILURE = 'FETCH_SINGLE_TVSHOW_FAILURE';

export const FETCH_TRAILER = 'FETCH_TRAILER';
export const FETCH_TRAILER_SUCCESS = 'FETCH_TRAILER_SUCCESS';
export const FETCH_TRAILER_FAILURE = 'FETCH_TRAILER_FAILURE';

export const FETCHING_ACTION_ADVENTURE = 'FETCHING_ACTION_ADVENTURE';
export const FETCHING_ACTION_ADVENTURE_SUCCESS = 'FETCHING_ACTION_ADVENTURE_SUCCESS';
export const FETCHING_ACTION_ADVENTURE_FAILURE = 'FETCHING_ACTION_ADVENTURE_FAILURE';

export const FETCHING_COMEDIES = 'FETCHING_COMEDIES';
export const FETCHING_COMEDIES_SUCCESS = 'FETCHING_COMEDIES_SUCCESS';
export const FETCHING_COMEDIES_FAILURE = 'FETCHING_COMEDIES_FAILURE';

export const FETCHING_DOCUMENTARIES = 'FETCHING_DOCUMENTARIES';
export const FETCHING_DOCUMENTARIES_SUCCESS = 'FETCHING_DOCUMENTARIES_SUCCESS';
export const FETCHING_DOCUMENTARIES_FAILURE = 'FETCHING_DOCUMENTARIES_FAILURE';

export const FETCHING_DRAMAS = 'FETCHING_DRAMAS';
export const FETCHING_DRAMAS_SUCCESS = 'FETCHING_DRAMAS_SUCCESS';
export const FETCHING_DRAMAS_FAILURE = 'FETCHING_DRAMAS_FAILURE';

export const FETCHING_KIDS = 'FETCHING_KIDS';
export const FETCHING_KIDS_SUCCESS = 'FETCHING_KIDS_SUCCESS';
export const FETCHING_KIDS_FAILURE = 'FETCHING_KIDS_FAILURE';

export const FETCHING_SCIFI = 'FETCHING_SCIFI';
export const FETCHING_SCIFI_SUCCESS = 'FETCHING_SCIFI_SUCCESS';
export const FETCHING_SCIFI_FAILURE = 'FETCHING_SCIFI_FAILURE';

export const FETCHING_FAMILY = 'FETCHING_FAMILY';
export const FETCHING_FAMILY_SUCCESS = 'FETCHING_FAMILY_SUCCESS';
export const FETCHING_FAMILY_FAILURE = 'FETCHING_FAMILY_FAILURE';
